trigger:
- main

pool:
  vmImage: 'Azure Pipelines'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install argocd-client
    wget https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -O argocd
    chmod +x argocd
    sudo mv argocd /usr/local/bin/
  displayName: 'Install Argo CD CLI'

- script: |
    argocd login $(ARGOCD_SERVER) --username admin --password $(ARGOCD_PASSWORD) --insecure
    argocd app create $(APP_NAME) \
      --repo $(GITHUB_URL) \
      --path $(FOLDER_NAME) \
      --dest-server $(KUBERNETES_CLUSTER_URL) \
      --dest-namespace $(NAMESPACE) \
      --sync-policy $(SYSC_POLICY)
  displayName: 'Deploy Application via Argo CD'
